# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDoctor(object):
    def setupUi(self, DialogDoctor):
        DialogDoctor.setObjectName("DialogDoctor")
        DialogDoctor.resize(400, 300)
        self.comboBoxP = QtWidgets.QComboBox(DialogDoctor)
        self.comboBoxP.setGeometry(QtCore.QRect(30, 60, 111, 22))
        self.comboBoxP.setCurrentText("")
        self.comboBoxP.setObjectName("comboBoxP")
        self.comboBox_2 = QtWidgets.QComboBox(DialogDoctor)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 60, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(DialogDoctor)
        self.comboBox_3.setGeometry(QtCore.QRect(220, 160, 111, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(DialogDoctor)
        self.comboBox_4.setGeometry(QtCore.QRect(30, 160, 111, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label = QtWidgets.QLabel(DialogDoctor)
        self.label.setGeometry(QtCore.QRect(60, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogDoctor)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogDoctor)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogDoctor)
        self.label_4.setGeometry(QtCore.QRect(260, 130, 61, 16))
        self.label_4.setObjectName("label_4")
        self.writeButton = QtWidgets.QPushButton(DialogDoctor)
        self.writeButton.setGeometry(QtCore.QRect(230, 240, 101, 31))
        self.writeButton.setObjectName("writeButton")
        self.backButton = QtWidgets.QPushButton(DialogDoctor)
        self.backButton.setGeometry(QtCore.QRect(30, 240, 101, 31))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(DialogDoctor)
        QtCore.QMetaObject.connectSlotsByName(DialogDoctor)

    def retranslateUi(self, DialogDoctor):
        _translate = QtCore.QCoreApplication.translate
        DialogDoctor.setWindowTitle(_translate("DialogDoctor", "Врач"))
        self.label.setText(_translate("DialogDoctor", "Профиль"))
        self.label_2.setText(_translate("DialogDoctor", "ФИО"))
        self.label_3.setText(_translate("DialogDoctor", "День"))
        self.label_4.setText(_translate("DialogDoctor", "Время"))
        self.writeButton.setText(_translate("DialogDoctor", "Записать"))
        self.backButton.setText(_translate("DialogDoctor", "Назад"))
