# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fix.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogFix(object):
    def setupUi(self, DialogFix):
        DialogFix.setObjectName("DialogFix")
        DialogFix.resize(400, 300)
        self.buttonDoctors = QtWidgets.QPushButton(DialogFix)
        self.buttonDoctors.setGeometry(QtCore.QRect(40, 50, 91, 31))
        self.buttonDoctors.setObjectName("buttonDoctors")
        self.buttonShedule = QtWidgets.QPushButton(DialogFix)
        self.buttonShedule.setGeometry(QtCore.QRect(40, 110, 91, 31))
        self.buttonShedule.setObjectName("buttonShedule")
        self.buttonPatients = QtWidgets.QPushButton(DialogFix)
        self.buttonPatients.setGeometry(QtCore.QRect(240, 50, 91, 31))
        self.buttonPatients.setObjectName("buttonPatients")
        self.buttonRecord = QtWidgets.QPushButton(DialogFix)
        self.buttonRecord.setGeometry(QtCore.QRect(240, 110, 91, 31))
        self.buttonRecord.setObjectName("buttonRecord")
        self.buttonLunch = QtWidgets.QPushButton(DialogFix)
        self.buttonLunch.setGeometry(QtCore.QRect(180, 210, 181, 41))
        self.buttonLunch.setObjectName("buttonLunch")

        self.retranslateUi(DialogFix)
        QtCore.QMetaObject.connectSlotsByName(DialogFix)

    def retranslateUi(self, DialogFix):
        _translate = QtCore.QCoreApplication.translate
        DialogFix.setWindowTitle(_translate("DialogFix", "Настройки"))
        self.buttonDoctors.setText(_translate("DialogFix", "Врачи"))
        self.buttonShedule.setText(_translate("DialogFix", "Расписание"))
        self.buttonPatients.setText(_translate("DialogFix", "Пациенты"))
        self.buttonRecord.setText(_translate("DialogFix", "Запись"))
        self.buttonLunch.setText(_translate("DialogFix", "Обеденный перерыв"))
